### PR TITLE
Add ignore_requirements parameter to check_requirements() method

### PR DESCRIPTION
**Pull request by audriusm**

### CODE REVIEW

**Comment by adamchainz** [comment]
Could you explain your use case a little more? Would it be better to parse and apply version markers?

**Comment by audriusm** [comment]
> Could you explain your use case a little more? Would it be better to parse and apply version markers?

Yes, this is a quick workaround for our failing `backports-zoneinfo` import case. The full implementation would add support for python version markers indeed.

**Comment by adamchainz** [comment]
Why did you close this? You no longer need it?

I was going to suggest, if you use `pip-compile` to compile your requirements for specific python versions, you won't need markers in your `requirements.txt` files.

**Comment by audriusm** [comment]
We just standardized on python 3.10 only and thus we don't have python version conditions in our requirements.txt any more.

I did not want to, somewhat, pressure you into accepting it or working on it, so decided to close it.

I think the best long term solution is to add version markers parsing to `pip-lock` functionality.

**Comment by adamchainz** [comment]
Thanks. I had an idea to use dparse for requirements parsing (#117), which would presumably parse markers. Evaluating them would be much harder though. There may be a pip internal we can try and use, but I've tried to avoid using such internals as they're not very stable.

I think I'll leave the feature for now, if someone else reports it then I'd consider it again.

**Pull request closed without merging**
